---
title: "Basics of programming"
author: "Jesus Sanchez"
date: '2022-10-17'
output: pdf_document
---
#Exploring data 

```{r}
library(tidyverse)

starwars
dim(starwars) #87 obs and 14 variables 
#str(starwars)
glimpse(starwars)
head(starwars) #first 6 obs
tail(starwars) #last 6 obs

attach(starwars) #this is useful to stop writing starwars$..., now I can write any variable of starwars without specify in which data set I am working
hair_color
names(starwars) #names of my variables
length(starwars) #for a data set length will mean the number of variables
length(hair_color) #for a variable R will tell the number of obs
class(hair_color)
unique(hair_color) #name of unique obs 
#na: data is missing 
#none: hair without a color or there´s no hair
#unknow: we don't know, maybe the character uses a hat, so we don't know the color

table(hair_color)
sort(table(hair_color), decreasing=T)
View(sort(table(hair_color), decreasing=T)) 
barplot(sort(table(hair_color), decreasing=T))

#pipes operators

starwars %>% 
  select(hair_color) %>% 
  count(hair_color) %>% 
  arrange(desc(n)) %>% 
  View()

View(starwars[is.na(hair_color),])  #selecting row where is.na is TRUE

summary(height)
boxplot(height) #boxplot 
hist(height) #histeogram
```

#Cleaning data 

```{r}
library(tidyverse)
data()
View(starwars)
glimpse(starwars)
unique(starwars$gender) #displays data type in the obs of a specific column
attach(starwars)

starwars$gender <- as.factor(starwars$gender)
class(starwars$gender)#now gender is a factor
class(starwars$gender)

levels(starwars$gender)
starwars$gender <- factor((starwars$gender), levels = c("f", "m"))
#changing levels

starwars %>% select(name, height, ends_with("color")) %>% 
  names()
unique(starwars$hair_color)

starwars %>% 
  select(name, height, ends_with("color")) %>% 
  filter(hair_color %in% c("blond", "brown") & height < 180)
#%in% works for group more than 1 variable 

#missing data

mean(starwars$height) #we have a NA because there's missin values Na
mean(starwars$height, na.rm = T)

starwars %>% 
  select(name, gender, hair_color, height) %>% 
  na.omit()

starwars %>% 
  select(name, gender, hair_color, height) %>% 
  filter(!complete.cases(.)) #what obs we deleted

starwars %>% 
  select(name, gender, hair_color, height) %>% 
  filter(!complete.cases(.)) %>% 
  drop_na(height) 

starwars %>% 
  select(name, gender, hair_color, height) %>% 
  filter(!complete.cases(.)) %>% 
  mutate(hair_color = replace_na(hair_color, "none"))
#replacing all NA values from hair_color

#Duplicates-------------------------------

Names <- c("Peter", "John", "Andrew", "Peter")
Age <- c(22,33,44,22)

friends <- data.frame(Names, Age)
duplicated(friends) #reporting duplicates

friends[!duplicated(friends), ] #the archaic method 

friends %>% distinct() #using tydiverse

#recording variables----------------------------------

starwars %>% select(name, gender)
class(starwars$gender)
starwars$gender <- as.factor(starwars$gender)
class(starwars$gender) #now we can recode the variable
levels(starwars$gender)

starwars %>% 
  select(name, gender) %>% 
  mutate(gender_coded = recode(gender, 
                         "masculine"= 1,
                         "feminine" = 2))

```


#Manipulating data

#Visualise

#Analyse







